NG_2023_Kanban/Models/ErrorViewModel.cs
namespace NG_2023_Kanban.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

NG_2023_Kanban/Controllers/AdminController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Http;
using AutoMapper;
using NG_2023_Kanban.Models;
using NG_2023_Kanban.DTOs;
using NG_2023_Kanban.BusinessLayer.Models;
using NG_2023_Kanban.BusinessLayer.Services;

namespace NG_2023_Kanban.Controllers;

public class AdminController : Controller
{
    private readonly UserService _userService;
    private readonly BoardService _boardService;
    private readonly ILogger<AdminController> _logger;
    private readonly IMapper _mapper;

    public AdminController(ILogger<AdminController> logger, UserService userService, BoardService boardService, IMapper mapper)
    {
        _logger = logger;
        _userService = userService;
        _boardService = boardService;
        _mapper = mapper;
    }

    public override async void OnActionExecuting(ActionExecutingContext actionContext)
    {
        var currentAccount = HttpContext.Session.GetInt32("Account");
        if (currentAccount.HasValue)
        {
            var userModel = await _userService.GetAsync(currentAccount.Value);
            bool isAdmin = await _userService.CheckAdminAsync(userModel.Id);
            if (!isAdmin)
            {
                actionContext.Result = StatusCode(403);
                return;
            }
            ViewData["Account"] = _mapper.Map<UserDto>(userModel);;
            ViewData["isAdmin"] = true;
        }
        else
            actionContext.Result = Redirect("/Auth/Login");
    }

    public async Task<IActionResult> Boards()
    {
        ViewData["Boards"] = _mapper.Map<ICollection<BoardDto>>(await _boardService.GetAllAsync());
        return View();
    }

    public async Task<IActionResult> Users()
    {
        ViewData["Users"] = _mapper.Map<ICollection<UserDto>>(await _userService.GetAllAsync());
        return View();
    }

    public async Task<IActionResult> EditUser(int id)
    {
        ViewData["EditedAccount"] = _mapper.Map<UserDto>(await _userService.GetAsync(id));
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> EditUser(int id, UserDto user)
    {
        ViewData["EditedAccount"] = _mapper.Map<UserDto>(await _userService.GetAsync(id));
        //try
        //{
            user.Id = id;
            var model = _mapper.Map<UserModel>(user);
            await _userService.UpdateAsync(id, model);
            return Redirect("/Admin/Users");
        //}
        //catch
        //{
        //    ViewData["Error"] = "This name is already taken.";
        //    return View();
        //}
    }

    public IActionResult CreateUser()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreateUser(UserDto user)
    {
        try
        {
            var model = _mapper.Map<UserModel>(user);
            await _userService.RegisterAsync(model);
            return Redirect("/Admin/Users");
        }
        catch
        {
            ViewData["Error"] = "This name is already taken.";
            return View();
        }
    }

    public async Task<IActionResult> DeleteUser(int id)
    {
        await _userService.DeleteAsync(id);
        return Redirect("/Admin/Users");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

NG_2023_Kanban/Controllers/AuthController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using AutoMapper;
using NG_2023_Kanban.Models;
using NG_2023_Kanban.DTOs;
using NG_2023_Kanban.BusinessLayer.Models;
using NG_2023_Kanban.BusinessLayer.Services;

namespace NG_2023_Kanban.Controllers;

public class AuthController : Controller
{
    private readonly UserService _userService;
    private readonly ILogger<AuthController> _logger;
    private readonly IMapper _mapper;

    public AuthController(ILogger<AuthController> logger, UserService userService, IMapper mapper)
    {
        _logger = logger;
        _userService = userService;
        _mapper = mapper;
    }

    public override void OnActionExecuting(ActionExecutingContext actionContext)
    {
        var currentAccount = HttpContext.Session.GetInt32("Account");
        if (currentAccount != null)
            actionContext.Result = Redirect("Home/Index");
    }

    public IActionResult Login()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Login(UserDto user)
    {
        var model = _mapper.Map<UserModel>(user);

        var account = _mapper.Map<UserDto>(await _userService.LoginAsync(model));

        if (account != null)
        {
            HttpContext.Session.SetInt32("Account", account.Id);
            return Redirect("/Home/Index");
        }
        else
        {
            ViewData["Error"] = "Invalid credentials.";
            return View();
        }
    }

    public IActionResult Register()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Register(UserDto user)
    {
        try
        {
            var model = _mapper.Map<UserModel>(user);
            var account = _mapper.Map<UserDto>(await _userService.RegisterAsync(model));

            HttpContext.Session.SetInt32("Account", account.Id);
            return Redirect("/Home/Index");
        }
        catch
        {
            ViewData["Error"] = "This name is already taken.";
            return View();
        }
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

NG_2023_Kanban/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using AutoMapper;
using NG_2023_Kanban.Models;
using NG_2023_Kanban.DTOs;
using NG_2023_Kanban.BusinessLayer.Models;
using NG_2023_Kanban.BusinessLayer.Services;

namespace NG_2023_Kanban.Controllers;

public class HomeController : Controller
{
    private readonly UserService _userService;
    private readonly ILogger<HomeController> _logger;
    private readonly IMapper _mapper;

    public HomeController(ILogger<HomeController> logger, UserService userService, IMapper mapper)
    {
        _logger = logger;
        _userService = userService;
        _mapper = mapper;
    }

    public override async void OnActionExecuting(ActionExecutingContext actionContext)
    {
        var currentAccount = HttpContext.Session.GetInt32("Account");
        if (currentAccount.HasValue)
        {
            var userModel = await _userService.GetAsync(currentAccount.Value);
            ViewData["Account"] = _mapper.Map<UserDto>(userModel);
            ViewData["isAdmin"] = await _userService.CheckAdminAsync(userModel.Id);
        }
        else
            actionContext.Result = Redirect("/Auth/Login");
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Logout()
    {
        HttpContext.Session.Remove("Account");
        return Redirect("/Auth/Login");
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

NG_2023_Kanban/Views/Admin/Boards.cshtml
@using NG_2023_Kanban.DTOs
@{
    var boards = ViewData["Boards"] as ICollection<BoardDto>;
}

@{
    ViewData["Title"] = "Boards";
}

<div class="text-center">
    <h1 class="display-4">Boards</h1>
    @{
        foreach (var board in boards)
        {
            <p>@board.Name | <a href="/Admin/EditBoard/@board.Id">Edit</a>, <a href="/Admin/DeleteBoard/@board.Id">Delete</a></p>
        }
        <p><a href="/Admin/AddBoard">New</a></p>
    }
</div>

NG_2023_Kanban/Views/Admin/CreateUser.cshtml
@using NG_2023_Kanban.DTOs
@{
    ViewData["Title"] = "Create user";
}

<div class="text-center">
    <h1 class="display-4">@ViewData["Title"]</h1>
@if (ViewData["Error"] != null)
{
    <p>@ViewData["Error"]</p>
}
    <form method="POST">
        <label for="fullName">Full name: </label><br>
        <input type="text" id="fullName" name="fullName" required><br>
        <label for="username">Username: </label><br>
        <input type="text" id="username" name="username" required><br>
        <label for="password">Password: </label><br>
        <input type="password" id="password" name="password" required><br>
        <button id="submit" type="submit">Submit</button>
    </form>
</div>

NG_2023_Kanban/Views/Admin/EditUser.cshtml
@using NG_2023_Kanban.DTOs
@{
     var user = ViewData["EditedAccount"] as UserDto;
 }

@{
    ViewData["Title"] = "Edit user";
}

<div class="text-center">
    <h1 class="display-4">@ViewData["Title"]</h1>
@if (ViewData["Error"] != null)
{
    <p>@ViewData["Error"]</p>
}
    <form method="POST">
        <label for="fullName">Full name: </label><br>
        <input type="text" id="fullName" name="fullName" value="@user.FullName" required><br>
        <label for="username">Username: </label><br>
        <input type="text" id="username" name="username" value="@user.Username" required><br>
        <label for="password">Password: </label><br>
        <input type="password" id="password" name="password"><br>
        <button id="submit" type="submit">Submit</button>
    </form>
</div>

NG_2023_Kanban/Views/Admin/Users.cshtml
@using NG_2023_Kanban.DTOs
@{
    var users = ViewData["Users"] as ICollection<UserDto>;
}

@{
    ViewData["Title"] = "Users";
}

<div class="text-center">
    <h1 class="display-4">Users</h1>
    @{
        foreach (var user in users)
        {
            <p>@user.Username | <a href="/Admin/EditUser/@user.Id">Edit</a>, <a href="/Admin/DeleteUser/@user.Id">Delete</a></p>
        }
        <p><a href="/Admin/CreateUser">New</a></p>
    }
</div>

NG_2023_Kanban/Views/Home/Index.cshtml
@using NG_2023_Kanban.DTOs
@{
     var user = ViewData["Account"] as UserDto;
 }

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <h2>@user.FullName</h2>
</div>

NG_2023_Kanban/Views/Shared/_Layout.cshtml
@using NG_2023_Kanban.DTOs
@{
     var user = ViewData["Account"] as UserDto;
 }

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NG_2023_Kanban</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NG_2023_Kanban.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NG_2023_Kanban</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        @if (user != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            if ((bool)ViewData["isAdmin"])
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Boards">Boards</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Users">Users</a>
                                </li>
                            }
                        }
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            @if (user == null)
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Log in</a>
                            }
                            else
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Log out</a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NG_2023_Kanban - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>